#ifndef POWER_MONITOR_DEFAULT_
#define POWER_MONITOR_DEFAULT_

// sensor
#define DEFAULT_ADC_ADDRESS "0x69"
#define DEFAULT_ADC_GAIN 1
#define DEFAULT_ADC_BITRATE 18
#define DEFAULT_ADC_MODE 1
#define DEFAULT_ADC_CHANNEL 1

// system
#define DEFAULT_ADC_RATE 1
#define DEFAULT_ADC_MULTIPLIER 11

// ros
#define DEFAULT_ROS_VOLTAGE_TOPIC "voltage"
#define DEFAULT_ROS_FRAME_ID "alpha"

#endif // POWER_MONITOR_DEFAULT_
